In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [3]:
df=pd.read_csv("C:\\Users\\Administrator\\Desktop\\Khoaluan\\dataclean.csv")

In [4]:
nan_values = df.isna()
nan_columns = nan_values.any()
columns_with_nan = df.columns[nan_columns].tolist()
columns_with_nan

['TinhTrangBDS',
 'TenPhanKhu',
 'SoTang',
 'GiayTo',
 'MaCanHo',
 'TinhTrangNoiThat',
 'HuongCuaChinh',
 'HuongBanCong',
 'DacDiem']

In [5]:
## Tỉ lệ NaN của các trường dữ liệu
df.isna().sum()/df.shape[0]*100

DiaChi               0.000000
Quan                 0.000000
TinhTrangBDS         0.007672
DienTich             0.000000
Phongngu             0.000000
TenPhanKhu          71.743133
SoTang              73.085776
PhongTam             0.000000
Loai                 0.000000
GiayTo              23.588308
MaCanHo             86.815252
TinhTrangNoiThat    48.553782
HuongCuaChinh       62.095289
HuongBanCong        64.788246
DacDiem             77.777352
Gia                  0.000000
USD                  0.000000
log_price            0.000000
dtype: float64

In [6]:

per = 0.5 # Chọn xóa những cột dữ liệu có trên 50% data là NaN

In [7]:
df_dropped = df.dropna(axis=1,thresh=int(df.shape[0]*per))
df_dropped

DiaChi               Quan  \
0      Đường Liên Phường, Phường Phú Hữu, Quận 9, Tp ...             Quận 9   
1      Lô 5, Lô 5 Khu đô thị Vĩnh Lộc, Phường Bình Hư...      Quận Bình Tân   
2      Đường Liên Phường, Phường Phú Hữu, Quận 9, Tp ...             Quận 9   
3      Đường Phạm Văn Đồng, Phường Linh Tây, Quận Thủ...       Quận Thủ Đức   
4      Số 8, Số 8 Đường Gò Dưa, Phường Hiệp Bình Phướ...       Quận Thủ Đức   
...                                                  ...                ...   
26063  Đường Xa lộ Hà Nội, Phường Hiệp Phú, Quận 9, T...             Quận 9   
26064  Lô 11B KĐT Nam Thành Phố, Lô 11B KĐT Nam Thành...   Huyện Bình Chánh   
26065  Đường Tạ Quang Bửu, Phường 5, Quận 8, Tp Hồ Ch...             Quận 8   
26066  Đường Phạm Văn Đồng, Phường 13, Quận Bình Thạn...    Quận Bình Thạnh   
26067  765 đường Hồng Bàng, Phường 6, Quận 6, Hồ Chí ...             Quận 6   

        TinhTrangBDS  DienTich  Phongngu  PhongTam      Loai       GiayTo  \
0        Đã bàn giao     50.00       2.0       1.0  Chung cư     Đã có sổ   
1        Đã bàn giao     63.00       2.0       2.0  Chung cư  Đang chờ sổ   
2        Đã bàn giao     53.00       2.0       1.0  Chung cư     Đã có sổ   
3        Đã bàn giao     75.00       2.0       2.0  Chung cư          NaN   
4        Đã bàn giao     57.72       2.0       2.0  Chung cư     Đã có sổ   
...              ...       ...       ...       ...       ...          ...   
26063    Đã bàn giao     53.00       2.0       1.0  Chung cư  Đang chờ sổ   
26064    Đã bàn giao     76.00       2.0       1.0  Chung cư     Đã có sổ   
26065    Đã bàn giao    115.00       2.0       2.0  Chung cư     Đã có sổ   
26066    Đã bàn giao     82.00       2.0       2.0  Chung cư     Đã có sổ   
26067  Chưa bàn giao     60.00       2.0       1.0  Chung cư  Đang chờ sổ   

        TinhTrangNoiThat           Gia       USD  log_price  
0      Hoàn thiện cơ bản  1.500000e+09   62500.0  11.042922  
1      Hoàn thiện cơ bản  1.650000e+09   68750.0  11.138232  
2                    NaN  1.600000e+09   66667.0  11.107465  
3                    NaN  1.850000e+09   77083.0  11.252638  
4      Hoàn thiện cơ bản  1.750000e+09   72917.0  11.197077  
...                  ...           ...       ...        ...  
26063  Hoàn thiện cơ bản  2.100000e+09   87500.0  11.379394  
26064   Nội thất cao cấp  1.550000e+09   64583.0  11.075706  
26065                NaN  3.300000e+09  137500.0  11.831379  
26066    Nội thất đầy đủ  2.650000e+09  110417.0  11.612019  
26067   Nội thất cao cấp  1.900000e+09   79167.0  11.279315  

[26068 rows x 12 columns]

In [8]:
df_dropped_2 = df_dropped.dropna(how='any')
#df_dropped_2 = df_dropped.dropna(axis=0,thresh=int(df.shape[1]*0.5))
df_dropped_2

DiaChi               Quan  \
0      Đường Liên Phường, Phường Phú Hữu, Quận 9, Tp ...             Quận 9   
1      Lô 5, Lô 5 Khu đô thị Vĩnh Lộc, Phường Bình Hư...      Quận Bình Tân   
4      Số 8, Số 8 Đường Gò Dưa, Phường Hiệp Bình Phướ...       Quận Thủ Đức   
6      Đường Phan Văn Hớn, Phường Tân Thới Nhất, Quận...            Quận 12   
7      Đường Nguyễn Xiển, Phường Long Thạnh Mỹ, Quận ...             Quận 9   
...                                                  ...                ...   
26062  Đường Tạ Quang Bửu, Phường 6, Quận 8, Tp Hồ Ch...             Quận 8   
26063  Đường Xa lộ Hà Nội, Phường Hiệp Phú, Quận 9, T...             Quận 9   
26064  Lô 11B KĐT Nam Thành Phố, Lô 11B KĐT Nam Thành...   Huyện Bình Chánh   
26066  Đường Phạm Văn Đồng, Phường 13, Quận Bình Thạn...    Quận Bình Thạnh   
26067  765 đường Hồng Bàng, Phường 6, Quận 6, Hồ Chí ...             Quận 6   

        TinhTrangBDS  DienTich  Phongngu  PhongTam      Loai       GiayTo  \
0        Đã bàn giao     50.00       2.0       1.0  Chung cư     Đã có sổ   
1        Đã bàn giao     63.00       2.0       2.0  Chung cư  Đang chờ sổ   
4        Đã bàn giao     57.72       2.0       2.0  Chung cư     Đã có sổ   
6        Đã bàn giao     65.00       2.0       2.0  Chung cư  Đang chờ sổ   
7        Đã bàn giao     69.00       2.0       2.0  Chung cư  Đang chờ sổ   
...              ...       ...       ...       ...       ...          ...   
26062    Đã bàn giao     68.00       2.0       2.0  Chung cư  Đang chờ sổ   
26063    Đã bàn giao     53.00       2.0       1.0  Chung cư  Đang chờ sổ   
26064    Đã bàn giao     76.00       2.0       1.0  Chung cư     Đã có sổ   
26066    Đã bàn giao     82.00       2.0       2.0  Chung cư     Đã có sổ   
26067  Chưa bàn giao     60.00       2.0       1.0  Chung cư  Đang chờ sổ   

        TinhTrangNoiThat           Gia       USD  log_price  
0      Hoàn thiện cơ bản  1.500000e+09   62500.0  11.042922  
1      Hoàn thiện cơ bản  1.650000e+09   68750.0  11.138232  
4      Hoàn thiện cơ bản  1.750000e+09   72917.0  11.197077  
6        Nội thất đầy đủ  1.760000e+09   73333.0  11.202766  
7       Nội thất cao cấp  1.120000e+09   46667.0  10.750793  
...                  ...           ...       ...        ...  
26062   Nội thất cao cấp  2.450000e+09  102083.0  11.533541  
26063  Hoàn thiện cơ bản  2.100000e+09   87500.0  11.379394  
26064   Nội thất cao cấp  1.550000e+09   64583.0  11.075706  
26066    Nội thất đầy đủ  2.650000e+09  110417.0  11.612019  
26067   Nội thất cao cấp  1.900000e+09   79167.0  11.279315  

[12903 rows x 12 columns]

In [9]:
df_dropped_2.to_csv('united3.csv',encoding="utf-8-sig",index=False)

In [10]:
df_dropped_2=pd.read_csv("united3.csv")

In [11]:
df_dropped_2

DiaChi               Quan  \
0      Đường Liên Phường, Phường Phú Hữu, Quận 9, Tp ...             Quận 9   
1      Lô 5, Lô 5 Khu đô thị Vĩnh Lộc, Phường Bình Hư...      Quận Bình Tân   
2      Số 8, Số 8 Đường Gò Dưa, Phường Hiệp Bình Phướ...       Quận Thủ Đức   
3      Đường Phan Văn Hớn, Phường Tân Thới Nhất, Quận...            Quận 12   
4      Đường Nguyễn Xiển, Phường Long Thạnh Mỹ, Quận ...             Quận 9   
...                                                  ...                ...   
12898  Đường Tạ Quang Bửu, Phường 6, Quận 8, Tp Hồ Ch...             Quận 8   
12899  Đường Xa lộ Hà Nội, Phường Hiệp Phú, Quận 9, T...             Quận 9   
12900  Lô 11B KĐT Nam Thành Phố, Lô 11B KĐT Nam Thành...   Huyện Bình Chánh   
12901  Đường Phạm Văn Đồng, Phường 13, Quận Bình Thạn...    Quận Bình Thạnh   
12902  765 đường Hồng Bàng, Phường 6, Quận 6, Hồ Chí ...             Quận 6   

        TinhTrangBDS  DienTich  Phongngu  PhongTam      Loai       GiayTo  \
0        Đã bàn giao     50.00       2.0       1.0  Chung cư     Đã có sổ   
1        Đã bàn giao     63.00       2.0       2.0  Chung cư  Đang chờ sổ   
2        Đã bàn giao     57.72       2.0       2.0  Chung cư     Đã có sổ   
3        Đã bàn giao     65.00       2.0       2.0  Chung cư  Đang chờ sổ   
4        Đã bàn giao     69.00       2.0       2.0  Chung cư  Đang chờ sổ   
...              ...       ...       ...       ...       ...          ...   
12898    Đã bàn giao     68.00       2.0       2.0  Chung cư  Đang chờ sổ   
12899    Đã bàn giao     53.00       2.0       1.0  Chung cư  Đang chờ sổ   
12900    Đã bàn giao     76.00       2.0       1.0  Chung cư     Đã có sổ   
12901    Đã bàn giao     82.00       2.0       2.0  Chung cư     Đã có sổ   
12902  Chưa bàn giao     60.00       2.0       1.0  Chung cư  Đang chờ sổ   

        TinhTrangNoiThat           Gia       USD  log_price  
0      Hoàn thiện cơ bản  1.500000e+09   62500.0  11.042922  
1      Hoàn thiện cơ bản  1.650000e+09   68750.0  11.138232  
2      Hoàn thiện cơ bản  1.750000e+09   72917.0  11.197077  
3        Nội thất đầy đủ  1.760000e+09   73333.0  11.202766  
4       Nội thất cao cấp  1.120000e+09   46667.0  10.750793  
...                  ...           ...       ...        ...  
12898   Nội thất cao cấp  2.450000e+09  102083.0  11.533541  
12899  Hoàn thiện cơ bản  2.100000e+09   87500.0  11.379394  
12900   Nội thất cao cấp  1.550000e+09   64583.0  11.075706  
12901    Nội thất đầy đủ  2.650000e+09  110417.0  11.612019  
12902   Nội thất cao cấp  1.900000e+09   79167.0  11.279315  

[12903 rows x 12 columns]

In [12]:
df_dropped_2.isna().sum()/df.shape[0]*100

DiaChi              0.0
Quan                0.0
TinhTrangBDS        0.0
DienTich            0.0
Phongngu            0.0
PhongTam            0.0
Loai                0.0
GiayTo              0.0
TinhTrangNoiThat    0.0
Gia                 0.0
USD                 0.0
log_price           0.0
dtype: float64

In [13]:
for i in range(0,len(df_dropped_2)):
    if df_dropped_2['Quan'][i]==' Quận 1':
        df_dropped_2['Quan'][i]=1
    elif df_dropped_2['Quan'][i]==' Quận 2':
        df_dropped_2['Quan'][i]=2
    elif df_dropped_2['Quan'][i]==' Quận 3':
        df_dropped_2['Quan'][i]=3
    elif df_dropped_2['Quan'][i]==' Quận 4':
        df_dropped_2['Quan'][i]=4
    elif df_dropped_2['Quan'][i]==' Quận 5':
        df_dropped_2['Quan'][i]=5
    elif df_dropped_2['Quan'][i]==' Quận 6':
        df_dropped_2['Quan'][i]=6
    elif df_dropped_2['Quan'][i]==' Quận 7':
        df_dropped_2['Quan'][i]=7
    elif df_dropped_2['Quan'][i]==' Quận 8':
        df_dropped_2['Quan'][i]=8
    elif df_dropped_2['Quan'][i]==' Quận 9':
        df_dropped_2['Quan'][i]=9
    elif df_dropped_2['Quan'][i]==' Quận 10':
        df_dropped_2['Quan'][i]=10
    elif df_dropped_2['Quan'][i]==' Quận 11':
        df_dropped_2['Quan'][i]=11
    elif df_dropped_2['Quan'][i]==' Quận 12':
        df_dropped_2['Quan'][i]=12
    elif df_dropped_2['Quan'][i]==' Quận Bình Tân':
        df_dropped_2['Quan'][i]=13 
    elif df_dropped_2['Quan'][i]==' Quận Thủ Đức':
        df_dropped_2['Quan'][i]=14
    elif df_dropped_2['Quan'][i]==' Quận Bình Thạnh':
        df_dropped_2['Quan'][i]=15 
    elif df_dropped_2['Quan'][i]==' Huyện Bình Chánh':
        df_dropped_2['Quan'][i]=16
    elif df_dropped_2['Quan'][i]==' Quận Tân Bình':
        df_dropped_2['Quan'][i]=17  
    elif df_dropped_2['Quan'][i]==' Huyện Nhà Bè':
        df_dropped_2['Quan'][i]=18
    elif df_dropped_2['Quan'][i]==' Quận Tân Phú':
        df_dropped_2['Quan'][i]=19
    elif df_dropped_2['Quan'][i]==' Quận Gò Vấp':
        df_dropped_2['Quan'][i]=20
    elif df_dropped_2['Quan'][i]==' Quận Phú Nhuận':
        df_dropped_2['Quan'][i]=21
    elif df_dropped_2['Quan'][i]==' Huyện Hóc Môn':
        df_dropped_2['Quan'][i]=22
    else:
        df_dropped_2['Quan'][i]=23



<ipython-input-13-6527cdae2e2b>:19: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_dropped_2['Quan'][i]=9
<ipython-input-13-6527cdae2e2b>:27: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_dropped_2['Quan'][i]=13
<ipython-input-13-6527cdae2e2b>:29: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_dropped_2['Quan'][i]=14
<ipython-input-13-6527cdae2e2b>:25: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice fro

In [14]:
df_dropped_2

DiaChi Quan   TinhTrangBDS  \
0      Đường Liên Phường, Phường Phú Hữu, Quận 9, Tp ...    9    Đã bàn giao   
1      Lô 5, Lô 5 Khu đô thị Vĩnh Lộc, Phường Bình Hư...   13    Đã bàn giao   
2      Số 8, Số 8 Đường Gò Dưa, Phường Hiệp Bình Phướ...   14    Đã bàn giao   
3      Đường Phan Văn Hớn, Phường Tân Thới Nhất, Quận...   12    Đã bàn giao   
4      Đường Nguyễn Xiển, Phường Long Thạnh Mỹ, Quận ...    9    Đã bàn giao   
...                                                  ...  ...            ...   
12898  Đường Tạ Quang Bửu, Phường 6, Quận 8, Tp Hồ Ch...    8    Đã bàn giao   
12899  Đường Xa lộ Hà Nội, Phường Hiệp Phú, Quận 9, T...    9    Đã bàn giao   
12900  Lô 11B KĐT Nam Thành Phố, Lô 11B KĐT Nam Thành...   16    Đã bàn giao   
12901  Đường Phạm Văn Đồng, Phường 13, Quận Bình Thạn...   15    Đã bàn giao   
12902  765 đường Hồng Bàng, Phường 6, Quận 6, Hồ Chí ...    6  Chưa bàn giao   

       DienTich  Phongngu  PhongTam      Loai       GiayTo   TinhTrangNoiThat  \
0         50.00       2.0       1.0  Chung cư     Đã có sổ  Hoàn thiện cơ bản   
1         63.00       2.0       2.0  Chung cư  Đang chờ sổ  Hoàn thiện cơ bản   
2         57.72       2.0       2.0  Chung cư     Đã có sổ  Hoàn thiện cơ bản   
3         65.00       2.0       2.0  Chung cư  Đang chờ sổ    Nội thất đầy đủ   
4         69.00       2.0       2.0  Chung cư  Đang chờ sổ   Nội thất cao cấp   
...         ...       ...       ...       ...          ...                ...   
12898     68.00       2.0       2.0  Chung cư  Đang chờ sổ   Nội thất cao cấp   
12899     53.00       2.0       1.0  Chung cư  Đang chờ sổ  Hoàn thiện cơ bản   
12900     76.00       2.0       1.0  Chung cư     Đã có sổ   Nội thất cao cấp   
12901     82.00       2.0       2.0  Chung cư     Đã có sổ    Nội thất đầy đủ   
12902     60.00       2.0       1.0  Chung cư  Đang chờ sổ   Nội thất cao cấp   

                Gia       USD  log_price  
0      1.500000e+09   62500.0  11.042922  
1      1.650000e+09   68750.0  11.138232  
2      1.750000e+09   72917.0  11.197077  
3      1.760000e+09   73333.0  11.202766  
4      1.120000e+09   46667.0  10.750793  
...             ...       ...        ...  
12898  2.450000e+09  102083.0  11.533541  
12899  2.100000e+09   87500.0  11.379394  
12900  1.550000e+09   64583.0  11.075706  
12901  2.650000e+09  110417.0  11.612019  
12902  1.900000e+09   79167.0  11.279315  

[12903 rows x 12 columns]

In [15]:
df_dropped_2.isna().sum()/df.shape[0]*100

DiaChi              0.0
Quan                0.0
TinhTrangBDS        0.0
DienTich            0.0
Phongngu            0.0
PhongTam            0.0
Loai                0.0
GiayTo              0.0
TinhTrangNoiThat    0.0
Gia                 0.0
USD                 0.0
log_price           0.0
dtype: float64

In [16]:
df_dropped_2.Quan.unique()

array([9, 13, 14, 12, 8, 17, 7, 6, 19, 2, 16, 1, 5, 4, 22, 21, 15, 10, 3,
       20, 18, 11, 23], dtype=object)

In [17]:
df_dropped_2.TinhTrangBDS.unique()


array(['Đã bàn giao', 'Chưa bàn giao'], dtype=object)

In [18]:
df_dropped_2.Loai.unique()

array(['Chung cư', 'Căn hộ dịch vụ', 'Duplex', 'Officetel', 'Penthouse',
       'Căn hộ dịch vụ, mini', 'Tập thể, cư xá'], dtype=object)

In [19]:
df_dropped_2.GiayTo.unique()

array(['Đã có sổ', 'Đang chờ sổ', 'Giấy tờ khác'], dtype=object)

In [20]:
df_dropped_2.TinhTrangNoiThat.unique()

array(['Hoàn thiện cơ bản', 'Nội thất đầy đủ', 'Nội thất cao cấp',
       'Bàn giao thô'], dtype=object)

In [21]:
for i in range(0,len(df_dropped_2)):
    if df_dropped_2['TinhTrangBDS'][i]=='Đã bàn giao':
        df_dropped_2['TinhTrangBDS'][i]=1
    else:
        df_dropped_2['TinhTrangBDS'][i]=2


<ipython-input-21-ff47e927a324>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_dropped_2['TinhTrangBDS'][i]=1
<ipython-input-21-ff47e927a324>:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_dropped_2['TinhTrangBDS'][i]=2


In [22]:
for i in range(0,len(df_dropped_2)):
    if df_dropped_2['Loai'][i]=='Chung cư':
        df_dropped_2['Loai'][i]=1
    elif df_dropped_2['Loai'][i]=='Căn hộ dịch vụ':
        df_dropped_2['Loai'][i]=2
    elif df_dropped_2['Loai'][i]=='Duplex':
        df_dropped_2['Loai'][i]=3
    elif df_dropped_2['Loai'][i]=='Officetel':
        df_dropped_2['Loai'][i]=4
    elif df_dropped_2['Loai'][i]=='Penthouse':
        df_dropped_2['Loai'][i]=5
    elif df_dropped_2['Loai'][i]=='Căn hộ dịch vụ, mini':
        df_dropped_2['Loai'][i]=6
    else:
        df_dropped_2['Loai'][i]=7

<ipython-input-22-95272fbb44c8>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_dropped_2['Loai'][i]=1
<ipython-input-22-95272fbb44c8>:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_dropped_2['Loai'][i]=2
<ipython-input-22-95272fbb44c8>:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_dropped_2['Loai'][i]=3
<ipython-input-22-95272fbb44c8>:9: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a Da

In [23]:
for i in range(0,len(df_dropped_2)):
    if df_dropped_2['TinhTrangNoiThat'][i]=='Hoàn thiện cơ bản':
        df_dropped_2['TinhTrangNoiThat'][i]=1
    elif df_dropped_2['TinhTrangNoiThat'][i]=='Nội thất đầy đủ':
        df_dropped_2['TinhTrangNoiThat'][i]=2
    elif df_dropped_2['TinhTrangNoiThat'][i]=='Nội thất cao cấp':
        df_dropped_2['TinhTrangNoiThat'][i]=3
    else:
        df_dropped_2['TinhTrangNoiThat'][i]=4

<ipython-input-23-815641dceb0c>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_dropped_2['TinhTrangNoiThat'][i]=1
<ipython-input-23-815641dceb0c>:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_dropped_2['TinhTrangNoiThat'][i]=2
<ipython-input-23-815641dceb0c>:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_dropped_2['TinhTrangNoiThat'][i]=3
<ipython-input-23-815641dceb0c>:9: SettingWithCopyWarning: 
A value is trying to b

In [24]:
 df_dropped_2



DiaChi Quan TinhTrangBDS  \
0      Đường Liên Phường, Phường Phú Hữu, Quận 9, Tp ...    9            1   
1      Lô 5, Lô 5 Khu đô thị Vĩnh Lộc, Phường Bình Hư...   13            1   
2      Số 8, Số 8 Đường Gò Dưa, Phường Hiệp Bình Phướ...   14            1   
3      Đường Phan Văn Hớn, Phường Tân Thới Nhất, Quận...   12            1   
4      Đường Nguyễn Xiển, Phường Long Thạnh Mỹ, Quận ...    9            1   
...                                                  ...  ...          ...   
12898  Đường Tạ Quang Bửu, Phường 6, Quận 8, Tp Hồ Ch...    8            1   
12899  Đường Xa lộ Hà Nội, Phường Hiệp Phú, Quận 9, T...    9            1   
12900  Lô 11B KĐT Nam Thành Phố, Lô 11B KĐT Nam Thành...   16            1   
12901  Đường Phạm Văn Đồng, Phường 13, Quận Bình Thạn...   15            1   
12902  765 đường Hồng Bàng, Phường 6, Quận 6, Hồ Chí ...    6            2   

       DienTich  Phongngu  PhongTam Loai       GiayTo TinhTrangNoiThat  \
0         50.00       2.0       1.0    1     Đã có sổ                1   
1         63.00       2.0       2.0    1  Đang chờ sổ                1   
2         57.72       2.0       2.0    1     Đã có sổ                1   
3         65.00       2.0       2.0    1  Đang chờ sổ                2   
4         69.00       2.0       2.0    1  Đang chờ sổ                3   
...         ...       ...       ...  ...          ...              ...   
12898     68.00       2.0       2.0    1  Đang chờ sổ                3   
12899     53.00       2.0       1.0    1  Đang chờ sổ                1   
12900     76.00       2.0       1.0    1     Đã có sổ                3   
12901     82.00       2.0       2.0    1     Đã có sổ                2   
12902     60.00       2.0       1.0    1  Đang chờ sổ                3   

                Gia       USD  log_price  
0      1.500000e+09   62500.0  11.042922  
1      1.650000e+09   68750.0  11.138232  
2      1.750000e+09   72917.0  11.197077  
3      1.760000e+09   73333.0  11.202766  
4      1.120000e+09   46667.0  10.750793  
...             ...       ...        ...  
12898  2.450000e+09  102083.0  11.533541  
12899  2.100000e+09   87500.0  11.379394  
12900  1.550000e+09   64583.0  11.075706  
12901  2.650000e+09  110417.0  11.612019  
12902  1.900000e+09   79167.0  11.279315  

[12903 rows x 12 columns]

In [25]:
df_dropped_2.Loai.unique()

array([1, 2, 3, 4, 5, 6, 7], dtype=object)

In [26]:
df_dropped_2.GiayTo.unique()

array(['Đã có sổ', 'Đang chờ sổ', 'Giấy tờ khác'], dtype=object)

In [27]:
for i in range(0,len(df_dropped_2)):
    if df_dropped_2['GiayTo'][i]=='Đã có sổ':
        df_dropped_2['GiayTo'][i]=1
    elif df_dropped_2['GiayTo'][i]=='Đang chờ sổ':
        df_dropped_2['GiayTo'][i]=2
    else:
        df_dropped_2['GiayTo'][i]=3

<ipython-input-27-ac06788c7427>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_dropped_2['GiayTo'][i]=1
<ipython-input-27-ac06788c7427>:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_dropped_2['GiayTo'][i]=2
<ipython-input-27-ac06788c7427>:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_dropped_2['GiayTo'][i]=3


In [28]:

df_dropped_2.to_csv('C:\\Users\\Administrator\\Desktop\\Khoaluan\\web\\united4.csv',encoding="utf-8-sig",index=False)
    

In [29]:
df_dropped_2

DiaChi Quan TinhTrangBDS  \
0      Đường Liên Phường, Phường Phú Hữu, Quận 9, Tp ...    9            1   
1      Lô 5, Lô 5 Khu đô thị Vĩnh Lộc, Phường Bình Hư...   13            1   
2      Số 8, Số 8 Đường Gò Dưa, Phường Hiệp Bình Phướ...   14            1   
3      Đường Phan Văn Hớn, Phường Tân Thới Nhất, Quận...   12            1   
4      Đường Nguyễn Xiển, Phường Long Thạnh Mỹ, Quận ...    9            1   
...                                                  ...  ...          ...   
12898  Đường Tạ Quang Bửu, Phường 6, Quận 8, Tp Hồ Ch...    8            1   
12899  Đường Xa lộ Hà Nội, Phường Hiệp Phú, Quận 9, T...    9            1   
12900  Lô 11B KĐT Nam Thành Phố, Lô 11B KĐT Nam Thành...   16            1   
12901  Đường Phạm Văn Đồng, Phường 13, Quận Bình Thạn...   15            1   
12902  765 đường Hồng Bàng, Phường 6, Quận 6, Hồ Chí ...    6            2   

       DienTich  Phongngu  PhongTam Loai GiayTo TinhTrangNoiThat  \
0         50.00       2.0       1.0    1      1                1   
1         63.00       2.0       2.0    1      2                1   
2         57.72       2.0       2.0    1      1                1   
3         65.00       2.0       2.0    1      2                2   
4         69.00       2.0       2.0    1      2                3   
...         ...       ...       ...  ...    ...              ...   
12898     68.00       2.0       2.0    1      2                3   
12899     53.00       2.0       1.0    1      2                1   
12900     76.00       2.0       1.0    1      1                3   
12901     82.00       2.0       2.0    1      1                2   
12902     60.00       2.0       1.0    1      2                3   

                Gia       USD  log_price  
0      1.500000e+09   62500.0  11.042922  
1      1.650000e+09   68750.0  11.138232  
2      1.750000e+09   72917.0  11.197077  
3      1.760000e+09   73333.0  11.202766  
4      1.120000e+09   46667.0  10.750793  
...             ...       ...        ...  
12898  2.450000e+09  102083.0  11.533541  
12899  2.100000e+09   87500.0  11.379394  
12900  1.550000e+09   64583.0  11.075706  
12901  2.650000e+09  110417.0  11.612019  
12902  1.900000e+09   79167.0  11.279315  

[12903 rows x 12 columns]

In [30]:
df_x = df_dropped_2.iloc[:, 1:9]
df_x

Quan TinhTrangBDS  DienTich  Phongngu  PhongTam Loai GiayTo  \
0        9            1     50.00       2.0       1.0    1      1   
1       13            1     63.00       2.0       2.0    1      2   
2       14            1     57.72       2.0       2.0    1      1   
3       12            1     65.00       2.0       2.0    1      2   
4        9            1     69.00       2.0       2.0    1      2   
...    ...          ...       ...       ...       ...  ...    ...   
12898    8            1     68.00       2.0       2.0    1      2   
12899    9            1     53.00       2.0       1.0    1      2   
12900   16            1     76.00       2.0       1.0    1      1   
12901   15            1     82.00       2.0       2.0    1      1   
12902    6            2     60.00       2.0       1.0    1      2   

      TinhTrangNoiThat  
0                    1  
1                    1  
2                    1  
3                    2  
4                    3  
...                ...  
12898                3  
12899                1  
12900                3  
12901                2  
12902                3  

[12903 rows x 8 columns]

In [31]:
df_y = df_dropped_2.iloc[:, 10]

df_y

0         62500.0
1         68750.0
2         72917.0
3         73333.0
4         46667.0
           ...   
12898    102083.0
12899     87500.0
12900     64583.0
12901    110417.0
12902     79167.0
Name: USD, Length: 12903, dtype: float64

In [32]:
#Split data 80% để train , 20% để test
X,X_test,Y,Y_test = train_test_split(df_x,df_y,test_size=0.2,random_state=365)

In [33]:
reg = LinearRegression().fit(X, Y)
reg.predict(X_test)

array([122625.56181155, 157149.96499105, 199425.07940597, ...,
        88112.52282661, 281373.07990457,  89853.12679406])

In [34]:
Y_test

11983    166667.0
1469     158333.0
2896     204167.0
5726      67500.0
9300        625.0
           ...   
11716     11667.0
10469    200000.0
217       81250.0
9085     187500.0
2120      27083.0
Name: USD, Length: 2581, dtype: float64

In [35]:
Y_pre = reg.predict(X_test)

In [36]:
Y_pre

array([122625.56181155, 157149.96499105, 199425.07940597, ...,
        88112.52282661, 281373.07990457,  89853.12679406])

In [37]:
perc = np.abs((Y_pre - Y_test)/Y_test)
perc = perc.values*100

In [38]:
np.array([Y_pre, Y_test, perc])

array([[1.22625562e+05, 1.57149965e+05, 1.99425079e+05, ...,
        8.81125228e+04, 2.81373080e+05, 8.98531268e+04],
       [1.66667000e+05, 1.58333000e+05, 2.04167000e+05, ...,
        8.12500000e+04, 1.87500000e+05, 2.70830000e+04],
       [2.64248101e+01, 7.47181579e-01, 2.32256956e+00, ...,
        8.44618194e+00, 5.00656426e+01, 2.31769475e+02]])

In [39]:

data = {'Gia du doan':Y_pre,
        'Gia thuc':Y_test,
       '% sai lech': perc}
A = pd.DataFrame(data)

In [40]:

B = A.sort_values(by=['% sai lech'])
B

Gia du doan  Gia thuc     % sai lech
801    37484.467569   37500.0       0.041420
4479   99952.605999  100000.0       0.047394
4787  154031.706701  154167.0       0.087758
8061  162280.761216  162500.0       0.134916
3877  166386.238608  166667.0       0.168456
...             ...       ...            ...
2274  176265.230177     156.0  112890.532164
6066  164564.225443     142.0  115790.299607
6969  103726.027853      83.0  124871.117895
5272  118495.424636      90.0  131561.582929
3945  183538.373537     119.0  154133.927342

[2581 rows x 3 columns]

In [41]:
B['% sai lech'].describe()

count      2581.000000
mean        715.282038
std        7386.689391
min           0.041420
25%          10.005389
50%          26.135026
75%          47.960236
max      154133.927342
Name: % sai lech, dtype: float64

In [42]:
B.to_csv("C:\\Users\\Administrator\\Desktop\\Khoaluan\\web\\saiso.csv")

In [43]:
perc

array([ 26.42481006,   0.74718158,   2.32256956, ...,   8.44618194,
        50.06564262, 231.76947456])

In [44]:
sum(perc)/len(Y_pre)

715.2820375549694

In [45]:
len(Y_pre)

2581

In [46]:
reg.predict([[9,1,50,2,1,1,1,1]])

array([69642.74845845])

In [47]:
reg.predict([[13,1,63,2,2,1,2,1]])

array([84090.43770953])

In [90]:
import pickle
pickle.dump(reg, open('C:\\Users\\Administrator\\Desktop\\Khoaluan\\web\\model1.pkl','wb'))

In [48]:
reg.predict([[12, 1, 65, 2, 2, 1, 2, 2]])

array([105768.3368632])