In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [2]:
df_dropped_2=pd.read_csv("C:\\Users\\Administrator\\Desktop\\Khoaluan\\web\\united4.csv")
               

In [3]:
df_dropped_2

DiaChi  Quan  TinhTrangBDS  \
0      Đường Liên Phường, Phường Phú Hữu, Quận 9, Tp ...     9             1   
1      Lô 5, Lô 5 Khu đô thị Vĩnh Lộc, Phường Bình Hư...    13             1   
2      Số 8, Số 8 Đường Gò Dưa, Phường Hiệp Bình Phướ...    14             1   
3      Đường Phan Văn Hớn, Phường Tân Thới Nhất, Quận...    12             1   
4      Đường Nguyễn Xiển, Phường Long Thạnh Mỹ, Quận ...     9             1   
...                                                  ...   ...           ...   
12898  Đường Tạ Quang Bửu, Phường 6, Quận 8, Tp Hồ Ch...     8             1   
12899  Đường Xa lộ Hà Nội, Phường Hiệp Phú, Quận 9, T...     9             1   
12900  Lô 11B KĐT Nam Thành Phố, Lô 11B KĐT Nam Thành...    16             1   
12901  Đường Phạm Văn Đồng, Phường 13, Quận Bình Thạn...    15             1   
12902  765 đường Hồng Bàng, Phường 6, Quận 6, Hồ Chí ...     6             2   

       DienTich  Phongngu  PhongTam  Loai  GiayTo  TinhTrangNoiThat  \
0         50.00       2.0       1.0     1       1                 1   
1         63.00       2.0       2.0     1       2                 1   
2         57.72       2.0       2.0     1       1                 1   
3         65.00       2.0       2.0     1       2                 2   
4         69.00       2.0       2.0     1       2                 3   
...         ...       ...       ...   ...     ...               ...   
12898     68.00       2.0       2.0     1       2                 3   
12899     53.00       2.0       1.0     1       2                 1   
12900     76.00       2.0       1.0     1       1                 3   
12901     82.00       2.0       2.0     1       1                 2   
12902     60.00       2.0       1.0     1       2                 3   

                Gia       USD  log_price  
0      1.500000e+09   62500.0  11.042922  
1      1.650000e+09   68750.0  11.138232  
2      1.750000e+09   72917.0  11.197077  
3      1.760000e+09   73333.0  11.202766  
4      1.120000e+09   46667.0  10.750793  
...             ...       ...        ...  
12898  2.450000e+09  102083.0  11.533541  
12899  2.100000e+09   87500.0  11.379394  
12900  1.550000e+09   64583.0  11.075706  
12901  2.650000e+09  110417.0  11.612019  
12902  1.900000e+09   79167.0  11.279315  

[12903 rows x 12 columns]

In [4]:
df_x = df_dropped_2.iloc[:, 1:9]
df_x

Quan  TinhTrangBDS  DienTich  Phongngu  PhongTam  Loai  GiayTo  \
0         9             1     50.00       2.0       1.0     1       1   
1        13             1     63.00       2.0       2.0     1       2   
2        14             1     57.72       2.0       2.0     1       1   
3        12             1     65.00       2.0       2.0     1       2   
4         9             1     69.00       2.0       2.0     1       2   
...     ...           ...       ...       ...       ...   ...     ...   
12898     8             1     68.00       2.0       2.0     1       2   
12899     9             1     53.00       2.0       1.0     1       2   
12900    16             1     76.00       2.0       1.0     1       1   
12901    15             1     82.00       2.0       2.0     1       1   
12902     6             2     60.00       2.0       1.0     1       2   

       TinhTrangNoiThat  
0                     1  
1                     1  
2                     1  
3                     2  
4                     3  
...                 ...  
12898                 3  
12899                 1  
12900                 3  
12901                 2  
12902                 3  

[12903 rows x 8 columns]

In [5]:
df_y = df_dropped_2.iloc[:, 10]

df_y

0         62500.0
1         68750.0
2         72917.0
3         73333.0
4         46667.0
           ...   
12898    102083.0
12899     87500.0
12900     64583.0
12901    110417.0
12902     79167.0
Name: USD, Length: 12903, dtype: float64

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
X, X_test, Y, Y_test = train_test_split(df_x,df_y, test_size = 0.2, random_state = 0)

In [31]:
from xgboost import XGBRegressor
reg  = XGBRegressor().fit(X, Y)

In [47]:
X_test

Quan  TinhTrangBDS  DienTich  Phongngu  PhongTam  Loai  GiayTo  \
11623    16             1      63.0       2.0       2.0     1       2   
11600    12             2      60.0       2.0       1.0     1       1   
5242     16             2      56.0       2.0       2.0     1       1   
5389     19             2      66.0       2.0       1.0     1       2   
12695    13             1      44.0       2.0       2.0     6       1   
...     ...           ...       ...       ...       ...   ...     ...   
9236      9             1      98.0       2.0       2.0     1       1   
6032     14             2     109.0       3.0       2.0     1       3   
12377    13             2      63.0       2.0       2.0     1       2   
10846    18             1      75.0       2.0       2.0     1       3   
1220      9             1      86.0       3.0       2.0     1       3   

       TinhTrangNoiThat  
11623                 4  
11600                 2  
5242                  1  
5389                  1  
12695                 3  
...                 ...  
9236                  2  
6032                  1  
12377                 2  
10846                 2  
1220                  3  

[2581 rows x 8 columns]

In [32]:
reg.predict(X_test)

array([ 90332.79 ,  67579.23 ,  52502.203, ...,  64375.45 ,  96902.59 ,
       130015.35 ], dtype=float32)

In [33]:
Y_test

11623     55000.0
11600     50000.0
5242      75000.0
5389      97917.0
12695     45833.0
           ...   
9236      56667.0
6032     162500.0
12377     68333.0
10846    135417.0
1220     145833.0
Name: USD, Length: 2581, dtype: float64

In [34]:
Y_pre = reg.predict(X_test)

In [35]:
Y_pre

array([ 90332.79 ,  67579.23 ,  52502.203, ...,  64375.45 ,  96902.59 ,
       130015.35 ], dtype=float32)

In [36]:
perc = np.abs((Y_pre - Y_test)/Y_test)
perc = perc.values*100

In [37]:
np.array([Y_pre, Y_test, perc])

array([[9.03327891e+04, 6.75792266e+04, 5.25022031e+04, ...,
        6.43754492e+04, 9.69025938e+04, 1.30015352e+05],
       [5.50000000e+04, 5.00000000e+04, 7.50000000e+04, ...,
        6.83330000e+04, 1.35417000e+05, 1.45833000e+05],
       [6.42414347e+01, 3.51584531e+01, 2.99970625e+01, ...,
        5.79156598e+00, 2.84413377e+01, 1.08464123e+01]])

In [38]:
data = {'Gia du doan':Y_pre,
        'Gia thuc':Y_test,
       '% sai lech': perc}
A = pd.DataFrame(data)

In [39]:

B = A.sort_values(by=['% sai lech'])
B

Gia du doan  Gia thuc     % sai lech
7016   108381.132812  108333.0       0.044430
12792   87448.632812   87500.0       0.058705
4770   100063.804688  100000.0       0.063805
6032   162364.515625  162500.0       0.083375
10363   83260.492188   83333.0       0.087010
...              ...       ...            ...
509     97393.195312     106.0   91780.372936
10238  101344.617188     110.0   92031.470170
6254    98683.546875     104.0   94788.025841
3777   130759.679688     115.0  113604.069293
5716   223646.406250     146.0  153082.470034

[2581 rows x 3 columns]

In [40]:
B['% sai lech'].describe()

count      2581.000000
mean        798.329312
std        7669.430486
min           0.044430
25%           2.278948
50%           9.319538
75%          25.577718
max      153082.470034
Name: % sai lech, dtype: float64

In [54]:
len(Y_pre)

2581

In [63]:
from sklearn.linear_model import Lasso
from sklearn.model_selection import GridSearchCV
lasso=Lasso()
parameters={'alpha':[1e-15,1e-10,1e-8,1e-3,1e-2,1,5,10,20,30,35,40,45,50,55,100]}
lasso_regressor=GridSearchCV(lasso,parameters,scoring='neg_mean_squared_error',cv=5)
lasso_regressor.fit(X,Y)


C:\Users\Administrator\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:530: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 267507452923815.9, tolerance: 57734555160.91866
  model = cd_fast.enet_coordinate_descent(
C:\Users\Administrator\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:530: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 267434415067254.12, tolerance: 58063912567.40875
  model = cd_fast.enet_coordinate_descent(
C:\Users\Administrator\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:530: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 262901644392632.9, tolerance: 56861498921.28823
  model = cd_fast.enet_coordinate_descent(
C:\Users\Administrator\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_

GridSearchCV(cv=5, estimator=Lasso(),
             param_grid={'alpha': [1e-15, 1e-10, 1e-08, 0.001, 0.01, 1, 5, 10,
                                   20, 30, 35, 40, 45, 50, 55, 100]},
             scoring='neg_mean_squared_error')

In [66]:
Y_pre1 = lasso_regressor.predict(X_test)

In [67]:
Y_pre1

array([125554.91068915,  90389.40872244,  48454.3818091 , ...,
        90137.45188619, 119601.01831732, 191451.94834734])

In [68]:
perc1 = np.abs((Y_pre1 - Y_test)/Y_test)
perc1 = perc1.values*100

In [69]:
np.array([Y_pre1, Y_test, perc1])

array([[1.25554911e+05, 9.03894087e+04, 4.84543818e+04, ...,
        9.01374519e+04, 1.19601018e+05, 1.91451948e+05],
       [5.50000000e+04, 5.00000000e+04, 7.50000000e+04, ...,
        6.83330000e+04, 1.35417000e+05, 1.45833000e+05],
       [1.28281656e+02, 8.07788174e+01, 3.53941576e+01, ...,
        3.19091096e+01, 1.16794654e+01, 3.12816361e+01]])

In [70]:
data = {'Gia du doan':Y_pre1,
        'Gia thuc':Y_test,
       '% sai lech': perc1}
A = pd.DataFrame(data)

In [71]:

B = A.sort_values(by=['% sai lech'])
B

Gia du doan  Gia thuc     % sai lech
11966   91743.459210   91667.0       0.083410
11800   62434.573655   62500.0       0.104682
134     75086.394451   75000.0       0.115193
9059    65911.898876   65833.0       0.119847
9583   158134.305875  158333.0       0.125491
...              ...       ...            ...
6623   104137.075679      85.0  122414.206682
10011  101833.440632      83.0  122590.892328
509    134728.883374     106.0  127002.720164
3777   153026.736951     115.0  132966.727784
6254   159663.410384     104.0  153422.509984

[2581 rows x 3 columns]

In [72]:
B['% sai lech'].describe()

count      2581.000000
mean        885.745424
std        8776.406788
min           0.083410
25%          10.725005
50%          27.220312
75%          46.493806
max      153422.509984
Name: % sai lech, dtype: float64

In [73]:
lasso_regressor.predict(([[12, 1, 65, 2, 2, 1, 2, 2]]))

array([106242.34544029])

In [74]:
lasso_regressor.predict([[9,1,50,2,1,1,1,1]])

array([72341.77672423])

In [8]:
from sklearn.tree import DecisionTreeRegressor
from sklearn import metrics
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import cross_val_score

In [9]:
random = RandomForestRegressor(max_depth=13, random_state=0)
random.fit(X,Y)

RandomForestRegressor(max_depth=13, random_state=0)

In [10]:
Y_pre2 = random.predict(X_test)

In [11]:
perc2 = np.abs((Y_pre2 - Y_test)/Y_test)
perc2 = perc2.values*100

In [12]:
np.array([Y_pre2, Y_test, perc2])

array([[7.69625855e+04, 6.21186271e+04, 5.54953670e+04, ...,
        6.68733415e+04, 9.67739525e+04, 1.14652560e+05],
       [5.50000000e+04, 5.00000000e+04, 7.50000000e+04, ...,
        6.83330000e+04, 1.35417000e+05, 1.45833000e+05],
       [3.99319736e+01, 2.42372542e+01, 2.60061773e+01, ...,
        2.13609604e+00, 2.85363340e+01, 2.13809220e+01]])

In [13]:
data = {'Gia du doan':Y_pre2,
        'Gia thuc':Y_test,
       '% sai lech': perc2}
A = pd.DataFrame(data)

In [14]:
B = A.sort_values(by=['% sai lech'])
B

Gia du doan  Gia thuc     % sai lech
2865   516667.000000  516667.0       0.000000
1118   516667.000000  516667.0       0.000000
9517   516667.000000  516667.0       0.000000
8304   516667.000000  516667.0       0.000000
4311   516667.000000  516667.0       0.000000
...              ...       ...            ...
10238  108086.956397     110.0   98160.869451
2158    97695.636049      98.0   99589.424540
3777   119551.742549     115.0  103858.036999
6254   109456.296582     104.0  105146.439021
5716   314718.212662     146.0  215460.419632

[2581 rows x 3 columns]

In [15]:
B['% sai lech'].describe()

count      2581.000000
mean        799.317589
std        8066.646935
min           0.000000
25%           2.425265
50%           9.044805
75%          24.806848
max      215460.419632
Name: % sai lech, dtype: float64

In [16]:
random.predict([[9,1,50,2,1,1,1,1]])

array([68801.43865956])

In [17]:
random.predict([[13,1,63,2,2,1,2,1]])

array([69445.81675459])

In [19]:
import pickle
pickle.dump(random, open('C:\\Users\\Administrator\\Desktop\\Khoaluan\\web\\model.pkl','wb'))